# Generated by Django 4.2.6 on 2023-10-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_alter_task_difficulty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reminder',
            old_name='time',
            new_name='alertTime',
        ),
        migrations.AlterField(
            model_name='reminder',
            name='startDate',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
