# Generated by Django 4.2.6 on 2023-11-03 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_difficulty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='reminders',
        ),
        migrations.DeleteModel(
            name='Reminder',
        ),
    ]
