# Generated by Django 4.2.6 on 2023-11-03 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_task_reminders_task_end_event_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='end_event',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_event',
            field=models.DateTimeField(null=True),
        ),
    ]
