# Generated by Django 4.2.6 on 2023-11-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_habit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurrencetask',
            name='recurrence_rule',
            field=models.CharField(),
        ),
    ]
