# Generated by Django 4.2.6 on 2023-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_alter_habit_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurrencetask',
            name='completion_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='completion_date',
            field=models.DateTimeField(null=True),
        ),
    ]
