# Generated by Django 4.2.6 on 2023-11-19 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_userstats_endurance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userstats',
            name='endurance',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='intelligence',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='luck',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='perception',
        ),
        migrations.RemoveField(
            model_name='userstats',
            name='strength',
        ),
        migrations.AddField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
